connection: "bigquery"
label: "Operational Monitoring"
# include: "//mozilla/operational_monitoring/explores/[!0-9]*"
# include: "//mozilla/operational_monitoring/dashboards/[!0-9]*"
include: "explores/preview.explore"
include: "dashboards/opmon-preview.dashboard"