---
version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-stage:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozillastaging.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-dev:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilladev.cloud.looker.com/webhooks/projects/spoke-default/deploy
  sync-dashboards-prod:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: src/sync_dashboards/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python ./src/sync_dashboards/main.py sync --config lookml_dashboards.yaml
          no_output_timeout: 15m
  validate-lookml:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install spectacles
          command: pip install spectacles==2.3.18
      - run:
          no_output_timeout: 20m
          command: |
            spectacles lookml \
              --base-url ${LOOKER_INSTANCE_URI} \
              --client-id ${LOOKER_API_CLIENT_ID} \
              --client-secret ${LOOKER_API_CLIENT_SECRET} \
              --project spoke-default \
              --remote-reset \
              --branch << pipeline.git.branch >>
workflows:
  version: 2
  build:
    jobs:
      - validate-lookml:
          context: data-eng-looker
      - deploy-prod:
          requires:
            - validate-lookml
          filters:
            branches:
              only: main
            tags:
              only: /.*/
      - deploy-stage:
          requires:
            - validate-lookml
          filters:
            branches:
              only: main-stage
            tags:
              only: /.*/
      - deploy-dev:
          requires:
            - validate-lookml
          filters:
            branches:
              only: main-nonprod
            tags:
              only: /.*/
      - sync-dashboards-prod:
          context: data-eng-looker
          requires:
            - deploy-prod
          filters:
            branches:
              only: main
            tags:
              only: /.*/
