---
version: 2.1
orbs:
  python: circleci/python@1.4.0
  docker: circleci/docker@2.2

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-stage:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozillastaging.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-dev:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilladev.cloud.looker.com/webhooks/projects/spoke-default/deploy
  sync-dashboards-prod:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: src/sync_dashboards/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python ./src/sync_dashboards/main.py sync --config lookml_dashboards.yaml
          no_output_timeout: 15m
  push-lookml-for-validation:
    executor: docker/machine
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:rVrow/3DEpsY1OTWFfA4PymfidEtdpLN37b8zb6lDQU"
      - run:
          name: Push lookml to main-validation branch
          command: |
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI main-validation job"
            git config --global user.email "dataops+main-validation@mozilla.com"
            git clone git@github.com:mozilla/looker-spoke-default /tmp/looker-spoke-default
            cd /tmp/looker-spoke-default
            git push origin main:main-validation
workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
      - deploy-stage:
          filters:
            branches:
              only: main-stage
            tags:
              only: /.*/
      - deploy-dev:
          filters:
            branches:
              only: main-nonprod
            tags:
              only: /.*/
      - sync-dashboards-prod:
          context: data-eng-looker
          requires:
            - deploy-prod
          filters:
            branches:
              only: main
            tags:
              only: /.*/
      - push-lookml-for-validation:
          filters:
            branches:
              only:
                - main
